name: DF-COMPILE

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2
      - name: Install project dependencies
        uses: docker://dataformco/dataform:1.6.11
        with:
          args: install
      - name: Run dataform compile
        uses: docker://dataformco/dataform:1.6.11
        with:
          args: compile
      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          fields: status,payload,text,author_name
        env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
          
          
# ['status', 'payload', 'mention', 'only_mention_fail', 'author_name', 'text', 'username', 'icon_emoji', 'icon_url', 'channel']
